# Generated by Django 3.1.2 on 2020-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'permissions': (('can_drive', '可以驾驶'), ('can_fix', '可以维修')),
            },
        ),
    ]
