# Generated by Django 3.1.2 on 2020-10-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201014_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(default=10, max_length=123),
        ),
        migrations.AddField(
            model_name='topping',
            name='name',
            field=models.CharField(default='配料', max_length=123),
        ),
    ]
