# Generated by Django 3.1.2 on 2020-10-16 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='没有以django开头', regex='django')])),
            ],
        ),
    ]
