# Generated by Django 3.1.2 on 2020-10-19 01:03

from django.db import migrations

def change_name(apps, schema_editor):
    Student = apps.get_model('blog', 'Student')
    for student in Student.objects.all():
        student.name = '%s %s' % (student.name, student.sex)
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201018_2103'),
    ]

    operations = [
        migrations.RunPython(change_name),
    ]
