# Generated by Django 3.1.2 on 2020-10-19 02:51

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Student = apps.get_model('blog', 'Student')
    for student in Student.objects.all():
        student.uuid = uuid.uuid4()
        student.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_student_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
