# Generated by Django 3.1.2 on 2020-10-19 02:52

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Student',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True)
        )
    ]
