# Generated by Django 3.1.2 on 2020-11-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['name']},
        ),
    ]
